### ISSUE TITLE
No longer works on latest version of Anki for me

### ISSUE THREAD

**Issue by alexander-newton** [achyutmorang/math-delimiters-replacer-addon#11]
Hi there,

I receive the following error when trying to use this addon on Anki.

Thanks for the addon.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Linux-6.5.12-300.fc39.x86_64-x86_64-with-glibc2.38
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-30 14:55:11
Add-ons possibly involved: ⁨Math Delimiters Replacer - LaTex MathJax   -⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 686, in _onBridgeCmd
  File "aqt.toolbar", line 411, in _linkHandler
  File "aqt.toolbar", line 426, in _addLinkHandler
  File "aqt.main", line 1230, in onAddCard
  File "aqt", line 136, in open
  File "aqt.addcards", line 50, in __init__
  File "aqt.addcards", line 77, in setupEditor
  File "aqt.editor", line 143, in __init__
  File "aqt.editor", line 196, in setupWeb
  File "anki.hooks", line 45, in runFilter
  File "/home/alexander/.var/app/net.ankiweb.Anki/data/Anki2/addons21/211799575/main.py", line 70, in setupEditorButtonsFilter
    tip=f"Replace Math Delimiters ({format_key(key)})",
  File "/home/alexander/.var/app/net.ankiweb.Anki/data/Anki2/addons21/211799575/main.py", line 26, in format_key
    return QKeySequence(k).toString(QKeySequence.NativeText)
AttributeError: type object 'QKeySequence' has no attribute 'NativeText'

**Comment by alexander-newton** [comment]
I think it might need to be 
```python
QKeySequence.SequenceFormat.NativeText
```
